baseURL: https://690591397.github.io/blog/
title: Hawkeye-xb Blog
theme: 
  - hugo-theme-stack

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

taxonomies:
  category: categories
  tag: tags
  series: series

defaultContentLanguage: zh
defaultContentLanguageInSubdir: true

params:
  mainSections:
    - posts
  colorScheme:
    toggle: true
    default: light
  comments:
    enabled: false